version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./server:/go/src/fit_record_server
    ports:
      - 3001:3001
  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    platform: linux/x86_64
    ports:
      - 3306:3306